### PR TITLE
Fix tests failing and save project attributes

### LINKED ISSUE #196: Project attributes are not saved
Projects are saved into the save file by Project tagNames. Upon load, a new Project object is created, leading to default values for the Project attributes.

### LINKED ISSUE #200: Tests Failing
Tests relating to `storage/JsonAdaptedPersonTest.java` are failing. Need to update test cases to match current expected behaviour.

### PR DESCRIPTION
**Pull request by kennethsoh**
Fixes test cases in #200 and bugs in #196 
Resolve #200 
Resolve #196

### CODE REVIEW

File: src/main/java/seedu/address/model/tag/Project.java [hunk 1]
```diff
@@ -14,6 +14,21 @@ public class Project extends Tag {
...
+     * @param tagName A valid tag name.
+     * @param isComplete Complete or Incomplete.
+     * @param isPaid Paid or Unpaid.
+     * @param deadline deadline in dd MMM yyyy HHmm format.
+     */
+    public Project(String tagName, String isComplete, String isPaid, String deadline) {
+        super(tagName);
+        this.isComplete = (isComplete.equals("Complete"));
+        this.isPaid = (isPaid.equals("Paid"));
+        this.deadline = LocalDateTime.parse(deadline.trim(), DateTimeFormatter.ofPattern("dd MMM yyyy HHmm"));
```
Comment (0x4F776C) [inline src/main/java/seedu/address/model/tag/Project.java:29]: Nice addition to Project class!

File: src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java [hunk 2]
```diff
@@ -88,7 +95,18 @@ public void toModelType_invalidTags_throwsIllegalValueException() {
...
+        assertThrows(IllegalValueException.class, person::toModelType);
+    }
+
+    @Test
+    public void toModelType_invalidProjects_throwsIllegalValueException() {
+        List<JsonAdaptedProject> invalidProjects = new ArrayList<>(VALID_PROJECTS);
+        invalidProjects.add(new JsonAdaptedProject(INVALID_PROJECT));
+        JsonAdaptedPerson person =
+                new JsonAdaptedPerson(VALID_NAME, VALID_PHONE, VALID_EMAIL, VALID_TAGS,
+                        invalidProjects, VALID_CONTACT_METHOD);
```
Comment (0x4F776C) [inline src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java:109]: Good fix for test case 👍🏼

File: src/main/java/seedu/address/storage/JsonAdaptedProject.java [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+import com.fasterxml.jackson.annotation.JsonProperty;
+
+import seedu.address.commons.exceptions.IllegalValueException;
+import seedu.address.model.tag.Project;
+import seedu.address.model.tag.Tag;
+
+/**
+ * Jackson-friendly version of {@link Project}.
+ */
+class JsonAdaptedProject {
```
Comment (0x4F776C) [inline src/main/java/seedu/address/storage/JsonAdaptedProject.java:13]: Great changes to the JsonAdaptedProject class! Looks much more complete now :D

**Review by 0x4F776C — APPROVED** [review]
LGTM

**Review by CJ-783 — APPROVED** [review]
LGTM 🧨 🔥
